// Download the site's four type families from Google Fonts into public/fonts/
// and emit the @font-face block that src/index.css carries.
//
// Why this exists: the site used to load fonts from fonts.googleapis.com, which
// told Google the IP address of every person who opened the Bali handbook. Spec
// CDT-00 moved the files in-house. This script is how they got here, so a weight
// change or a family addition is a re-run rather than an archaeology exercise.
//
// Usage:
//   node scripts/fetch-fonts.mjs            # download + print the CSS
//   node scripts/fetch-fonts.mjs --check    # re-fetch and report drift, no writes
//
// Google serves pre-subsetted woff2 per unicode-range, so "subset to Latin plus
// Latin Extended" is a matter of keeping two of the seven ranges it offers
// rather than running a subsetter locally.

import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Playfair+Display:wght@400;600;700' +
  '&family=Lora:ital,wght@0,400;0,500;0,600;1,400' +
  '&family=Source+Sans+3:wght@400;500;600;700' +
  '&family=Caveat:wght@500' +
  '&display=swap'

// A modern browser UA is required, or Google serves ttf with no unicode-range.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

const KEEP = new Set(['latin', 'latin-ext'])
const OUT_DIR = path.join(process.cwd(), 'public', 'fonts')
const checkOnly = process.argv.includes('--check')

const slug = (family) => family.toLowerCase().replace(/\s+/g, '-')

function parse(css) {
  const faces = []
  // Each @font-face is preceded by a `/* subset */` comment.
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g
  let m
  while ((m = re.exec(css))) {
    const [, subset, body] = m
    const field = (name) => (body.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim()
    const url = (body.match(/url\(([^)]+)\)/) || [])[1]
    faces.push({
      subset,
      family: field('font-family').replace(/['"]/g, ''),
      style: field('font-style'),
      weight: field('font-weight'),
      unicodeRange: field('unicode-range'),
      url,
    })
  }
  return faces
}

// Google declares one @font-face per weight but points several of them at the
// SAME woff2, because the file is a variable font. Playfair 400/600/700 share
// one file; Source Sans 400/500/600/700 share one. So the file name is keyed on
// family + style + subset, NOT on weight: keying on weight saves the same bytes
// three times, which is how the first run of this script tripled the font
// payload and pushed home-page LCP from 108ms to 824ms.
//
// The @font-face blocks stay one-per-weight exactly as Google writes them, so
// rendering is identical; only the URL they point at changes.
const fileName = (f) =>
  `${slug(f.family)}${f.style === 'italic' ? '-italic' : ''}.${f.subset}.woff2`

function cssFor(faces) {
  const lines = [
    '/* SIL\'s type stack, self-hosted. Generated by scripts/fetch-fonts.mjs;',
    '   see docs/SECURITY.md for why these are not loaded from Google. */',
  ]
  for (const f of faces) {
    lines.push(
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${fileName(f)}') format('woff2');`,
      `  unicode-range: ${f.unicodeRange};`,
      '}',
    )
  }
  return lines.join('\n') + '\n'
}

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`)
  return r.text()
})

const all = parse(css)
const faces = all
  .filter((f) => KEEP.has(f.subset))
  .sort((a, b) =>
    a.family.localeCompare(b.family) ||
    a.style.localeCompare(b.style) ||
    Number(a.weight) - Number(b.weight) ||
    a.subset.localeCompare(b.subset),
  )

const familyFaceCount = new Map()
for (const f of faces) {
  const key = `${f.family} ${f.style} ${f.weight}`
  familyFaceCount.set(key, (familyFaceCount.get(key) || 0) + 1)
}
console.log(
  `parsed ${all.length} @font-face blocks across ${new Set(all.map((f) => f.subset)).size} subsets`,
)
console.log(
  `keeping ${faces.length} files for ${familyFaceCount.size} faces ` +
    `(${[...KEEP].join(' + ')})`,
)
// Twelve faces: Playfair Display 400/600/700, Lora 400/500/600 plus italic 400,
// Source Sans 3 400/500/600/700, Caveat 500. Spec CDT-00 said fifteen; the
// re-measure said twelve and the spec was corrected rather than the gate.
const EXPECTED_FACES = 12
if (familyFaceCount.size !== EXPECTED_FACES) {
  throw new Error(
    `expected ${EXPECTED_FACES} faces, Google served ${familyFaceCount.size}: ` +
      [...familyFaceCount.keys()].join(', '),
  )
}

if (checkOnly) {
  const onDisk = new Set((await readdir(OUT_DIR)).filter((n) => n.endsWith('.woff2')))
  let drift = 0
  const uniq = new Map(faces.map((f) => [fileName(f), f]))
  for (const [, f] of uniq) {
    const name = fileName(f)
    if (!onDisk.delete(name)) {
      console.log(`MISSING ${name}`)
      drift++
      continue
    }
    const [remote, local] = await Promise.all([
      fetch(f.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
      readFile(path.join(OUT_DIR, name)),
    ])
    const h = (b) => createHash('sha256').update(Buffer.from(b)).digest('hex').slice(0, 12)
    if (h(remote) !== h(local)) {
      console.log(`CHANGED ${name}  remote ${h(remote)} local ${h(local)}`)
      drift++
    }
  }
  for (const extra of onDisk) {
    console.log(`EXTRA   ${extra}`)
    drift++
  }
  console.log(drift ? `drift: ${drift}` : 'no drift: disk matches Google')
  process.exit(drift ? 1 : 0)
}

// One download per unique file, and an assertion that the naming key holds: two
// different URLs landing on one name would silently overwrite a face.
const byName = new Map()
for (const f of faces) {
  const name = fileName(f)
  const prior = byName.get(name)
  if (prior && prior.url !== f.url) {
    throw new Error(
      `two different files want the name ${name}:\n  ${prior.url}\n  ${f.url}\n` +
        'The family+style+subset key no longer identifies one file; add weight back.',
    )
  }
  if (!prior) byName.set(name, { url: f.url, weights: [] })
  byName.get(name).weights.push(`${f.weight}${f.style === 'italic' ? 'i' : ''}`)
}

await mkdir(OUT_DIR, { recursive: true })
let bytes = 0
for (const [name, { url, weights }] of [...byName].sort()) {
  const buf = Buffer.from(
    await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
      if (!r.ok) throw new Error(`${url} returned ${r.status}`)
      return r.arrayBuffer()
    }),
  )
  bytes += buf.length
  await writeFile(path.join(OUT_DIR, name), buf)
  console.log(`  ${name.padEnd(34)} ${(buf.length / 1024).toFixed(1).padStart(6)} KB  serves weights ${weights.join('/')}`)
}
console.log(
  `total ${(bytes / 1024).toFixed(1)} KB across ${byName.size} files ` +
    `for ${faces.length} @font-face declarations`,
)
const latinOnly = [...byName].filter(([n]) => n.endsWith('.latin.woff2'))
console.log(
  `of which ${latinOnly.length} are the Latin subset a visitor actually fetches; ` +
    'latin-ext downloads only when a page contains such a character',
)

const cssPath = path.join(process.cwd(), 'scripts', 'fonts.generated.css')
await writeFile(cssPath, cssFor(faces))
console.log(`\n@font-face block written to ${path.relative(process.cwd(), cssPath)}`)
console.log('Paste it into src/index.css above the @theme block.')
